apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user-story
  labels:
    app: api-user-story
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-user-story
  template:
    metadata:
      labels:
        app: api-user-story
    spec:
      containers:
        - name: api-user-story
          image: mannmengineer/lowcode-api-user-story
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
            - secretRef:
                name: aws-secret
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
